# Generated by Django 5.2 on 2025-04-13 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juego',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria'),
        ),
        migrations.AlterField(
            model_name='juego',
            name='descripcion',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='juego',
            name='imagen',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='juego',
            name='plataformas',
            field=models.CharField(max_length=255),
        ),
    ]
