# Generated by Django 5.2 on 2025-04-12 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_juego_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=200)),
                ('nombre_usuario', models.CharField(max_length=150, unique=True)),
                ('correo_electronico', models.EmailField(max_length=254, unique=True)),
                ('contrasena', models.CharField(max_length=255)),
                ('repetir_contrasena', models.CharField(max_length=255)),
                ('fecha_nacimiento', models.DateField()),
                ('direccion_despacho', models.CharField(blank=True, max_length=255, null=True)),
                ('rol', models.IntegerField(choices=[(1, 'Administrador'), (2, 'Vendedor'), (3, 'Cliente'), (4, 'Invitado')], default=4)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
    ]
