# Generated by Django 5.2 on 2025-04-12 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='repetir_contrasena',
        ),
    ]
