# Generated by Django 5.2 on 2025-04-13 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_juego_categoria_alter_juego_descripcion_and_more'),
        ('core', '0006_alter_usuario_nombre_usuario_alter_usuario_rol'),
    ]

    operations = [
    ]
