# Generated by Django 5.2 on 2025-04-14 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_merge_20250413_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juego',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.categoria'),
        ),
        migrations.AlterField(
            model_name='juego',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='juego',
            name='imagen',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='juego',
            name='plataformas',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
