# Generated by Django 5.2 on 2025-05-01 05:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_contacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='respuesta',
            field=models.TextField(blank=True, null=True, verbose_name='Respuesta'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de envío'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='leido',
            field=models.BooleanField(default=False, verbose_name='¿Leído?'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='mensaje',
            field=models.TextField(verbose_name='Mensaje'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre completo'),
        ),
        migrations.AlterModelTable(
            name='contacto',
            table=None,
        ),
    ]
